alphavantage:
  api:
    key: NN2E3WQP66461VB6
    url: https://www.alphavantage.co/query
server:
  error:
    whitelabel:
      enabled: false
spring:
  mvc:
    throw-exception-if-no-handler-found: true
